/*
* create by Falcon
* date: 06/05/2019
*/
import { 
  homeTest,
  difficulty,
  totalZTR,
  usageToken,
  totalToken,
  feeTradingPowerMax
  } from './home'
import { 
  openOrderLimit,
  filledOrderLimit,
  openOrderList,
  filledOrderList,
  lockTradingPowerList,
  tradingPower,
  userBalance,
  tradingPowerLock,
  userToken,
  accountAddress,
  userZethyr,
  userRewardPoint,
  listBlock,
  ecoPower,
  ecoPowerBlock,
  votingPower,
  votingPowerLock,
  loadPage,
  userTrx,
  userDividends,
  userAvailableBalance,
  pageLockToken,
  numberPageTradingPower,
  pageLockVoitingPower,
  numberPageVoitingPower,
  pageLockEcoPower,
  numberPageEcoPower,
  pageOpenOder,
  numberPageOpenOder, 
  pageOpenHistory,
  numberPageOpenHistory,
  timeEndRound,
  timeStartRound,
  totalEcoPower,
  totalDividends,
  weekDividends,
  numberLockByDayTrading,
  numberLockByDayEco,
  numberLockByDayVoiting
  } from './user'

import { 
  cryptoNews,
  coinList,
	tradeListToken, 
	tradeIdActive,
	tradeOrderBuyList,
  tradeOrderSellList, 
  tradeOrderBuyActive, 
	tradeOrderSellActive,
  tradeHistoryList,
  tradeCheckLogin,
  tradeSortByDecimal,
  tradeLastHistory,
  checkRegister,
  priceLastTrade,
  tradeToken,
  priceToken,
  priceUsdOnTrx,
  checkMarketToken,
  loadOderTokenWhenChange,
  tradePriceToken,
  freeTradingQuota,
  changeLang,
  placeholderInputValue,
  tradingPowerPageTrade


} from './trade'

import { 
  blogPage,
  blogList,
  blogNumberPage,
  blogSlug,
  blogDetail
} from './blog'

export default {
  homeTest,
  difficulty,
  totalZTR,
  usageToken,
  totalToken,
  feeTradingPowerMax,
  /** -----------* exchange *--------------------*/
  cryptoNews,
  coinList,
  tradeListToken,
  tradeIdActive,
  tradeOrderBuyList,
  tradeOrderSellList, 
  tradeOrderBuyActive, 
  tradeOrderSellActive,
  tradeHistoryList,
  tradeCheckLogin,
  tradeSortByDecimal,
  tradeLastHistory,
  checkRegister,
  priceLastTrade,
  tradeToken,
  priceToken,
  priceUsdOnTrx,
  checkMarketToken,
  loadOderTokenWhenChange,
  tradePriceToken,
  freeTradingQuota,
  tradingPowerPageTrade,
  changeLang,
  placeholderInputValue,
  /*------------* user *---------------*/
  lockTradingPowerList,
  openOrderLimit,
  filledOrderLimit,
  openOrderList,
  filledOrderList,
  tradingPower,
  userBalance,
  tradingPowerLock,
  userToken,
  accountAddress,
  userZethyr,
  userRewardPoint,
  listBlock,
  ecoPower,
  ecoPowerBlock,
  votingPower,
  votingPowerLock,
  loadPage,
  userTrx,
  userDividends,
  userAvailableBalance,
  /*------------* user *---------------*/
  blogPage,
  blogList,
  blogNumberPage,
  blogSlug,
  blogDetail,
  pageLockToken,
  numberPageTradingPower,
  pageLockVoitingPower,
  numberPageVoitingPower,
  pageLockEcoPower,
  numberPageEcoPower,
  pageOpenOder,
  numberPageOpenOder,
  pageOpenHistory,
  numberPageOpenHistory,
  timeEndRound,
  timeStartRound,
  totalEcoPower,
  totalDividends,
  weekDividends,
  numberLockByDayTrading,
  numberLockByDayEco,
  numberLockByDayVoiting
}